SVNDev/backend/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

from backend_admin import views as backend_admin_view

handler403 = backend_admin_view.perm_deny
handler404 = backend_admin_view.page_no

urlpatterns = [
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, }),
    url(r'', include('backend_admin.urls', namespace='backend_admin'), ),
    url(r'^config/', include('config.urls', namespace='config'), ),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^allsite/', include('allsite.urls', namespace='allsite'), ),
    url(r'^comments/', include('comments.urls', namespace='comments'), ),
    url(r'^channels/', include('channelConfigMgr.urls', namespace='channels'), ),
]

SVNDev/backend_admin/urls.py
from django.conf.urls import url, patterns
from . import views
from django.views.generic import RedirectView

# from django.views.generic.simple import redirect_to

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login_view, name='login'),
    url(r'^logout$', views.logout_view, name='logout'),
    url(r'^changepassword$', views.change_password, name='change_password'),
    url(r'^private$', views.private, name='private'),
    url(r'^backend_admin/backend_admin/user/add/$', views.create_user, name='create_user', ),
    url(r'^backend_admin/backend_admin/user/(\d+)/password$', views.change_user_password, name='change_user_password', ),
    url(r'^backend_admin/backend_admin/user/(\d+)/$', views.change_user, name='change_user', ),
    url(r'^backend_admin/auth/group/add/$', views.add_group, name='add_group', ),
    url(r'^backend_admin/auth/group/(\d+)/$', views.change_group, name='change_group', ),
    # url(r'^admin/backend_admin/user/\d/$', RedirectView.as_view(url='/changeuser'),),
    # url(r'^admin/auth/group/$', RedirectView.as_view(url='/backend_admin/auth/group', permanent=True), ),

    url(r'^duplicate_username$', views.username_duplicate_verify, name='duplicate_username'),
    url(r'^duplicate_email$', views.email_duplicate_verify, name='duplicate_email'),
    url(r'^backend_admin/(\w+)/(\w+)/$', views.change_list, name='change_list'),
    url(r'^backend_admin/(\w+)/(\w+)/delete$', views.model_object_delete, name='model_object_delete'),

    url(r'^uwsgireload/$', views.reload_uwsgi, name='reload_uwsgi'),
]

SVNDev/config/urls.py
from django.conf.urls import url, patterns
from django.views.generic import RedirectView
# from django.views.generic.simple import redirect_to

from . import views
from config import rest_api


urlpatterns = [
    url(r'^$', views.select_configs, name='select'),
    url(r'^groups/$', views.config_groups_list, name='group'),
    url(r'^groups/(\d+)/$', views.config_group_change, name='each_change'),
    url(r'^groups/add/$', views.config_group_add, name='each_add'),
    url(r'^groups/delete/$', views.config_group_delete, name='each_delete'),
    url(r'^groups/api/$', rest_api.ConfigGroupsListApi.as_view(), name='config_groups_list_api'),

    url(r'^add/$', views.add_config, name='add_config'),
    url(r'^(\d+)/change/$', views.change_config, name='change_config'),
    url(r'^(\d+)/change/history/$', views.change_history, name='change_history'),
    url(r'^diff/$', views.change_config_diff, name='change_diff'),

    # 时间差统计
    url(r'^delta/news/domain/domain$', views.news_user_timedelta_view, name='news_user_timedelta_view'),
    url(r'^delta/news/domain/domain/search/$', views.news_user_timedelta_view, name='news_user_timedelta_view_search'),
    url(r'^delta/news/domain/users/$', views.news_all_user_timedelta_view, name='news_all_user_timedelta_view'),
    url(r'^delta/news/domain/users/search/$', views.news_all_user_timedelta_view, name='news_all_user_timedelta_view_search'),
    url(r'^delta/news/config/config/$', views.config_timedelta_view, name='config_timedelta_view'),
    url(r'^delta/news/config/config/search/$', views.config_timedelta_view, name='config_timedelta_view_search'),
    url(r'^delta/news/config/groupsexclude/$', views.config_groupsexclude_delta, name='config_groupsexclude_delta'),
    url(r'^delta/news/config/groupsexclude/search/$', views.config_groupsexclude_delta, name='config_groupsexclude_delta_search'),

    url(r'^delta/forums/domain/domain$', views.forums_user_timedelta_view, name='forums_user_timedelta_view'),
    url(r'^delta/forums/domain/domain/search/$', views.forums_user_timedelta_view, name='forums_user_timedelta_view_search'),
    url(r'^delta/forums/domain/users/$', views.forums_all_user_timedelta_view, name='forums_all_user_timedelta_view'),
    url(r'^delta/forums/domain/users/search/$', views.forums_all_user_timedelta_view, name='forums_all_user_timedelta_view_search'),
    url(r'^delta/forums/config/config/$', views.forums_config_timedelta_view, name='forums_config_timedelta_view'),
    url(r'^delta/forums/config/config/search/$', views.forums_config_timedelta_view, name='forums_config_timedelta_view_search'),

    url(r'^delta/alldomains/$', views.all_domains_timedelta_view, name='all_domains_timedelta_view'),
    url(r'^delta/alldomains/search/$', views.all_domains_timedelta_view, name='all_domains_timedelta_view_search'),
    url(r'^delta/allconfigs/$', views.all_configs_timedelta_view, name='all_configs_timedelta_view'),
    url(r'^delta/allconfigs/search/$', views.all_configs_timedelta_view, name='all_configs_timedelta_view_search'),

    # 时间差排除
    url(r'^delta/exclude/(\w+)/(\w+)/(\w+)/$', views.exclude_manage, name='exclude_manage'),
    url(r'^delta/excludegroups/(\w+)/(\w+)/(\w+)/$', views.exclude_groups_manage, name='exclude_groups_manage'),

    # 时间差总数
    # url(r'^delta/sum/(\w+)/$', views.sum_deltas, name='sum_deltas'),
    url(r'^delta/basesum/(\w+)/(\w+)/(\w+)/(\S*)/$', views.base_sum_deltas, name='base_sum_deltas'),
    url(r'^delta/ranksum/(\w+)/(\w+)/(\w+)/(\S*)/(\d+)/$', views.rank_sum_deltas, name='rank_sum_deltas'),
    url(r'^delta/customsum/(\w+)/(\w+)/(\w+)/(\S*)/$', views.custom_sum_deltas, name='custom_sum_deltas'),
    url(r'^delta/searchsum/(\w+)/(\w+)/(\w+)/(\S*)/$', views.search_sum_deltas, name='search_sum_deltas'),

    # 时间差历史
    url(r'^delta/history/news/(\w+)/(\w+)/(\S*)/$', views.time_delta_history_view, name='time_delta_history_view'),

    url(r'^delta/history/sum/(\w+)/(\w+)/(\w+)/$', views.sum_delta_history_view, name='sum_delta_history_view'),
    url(r'^delta/history/searchsum/(\w+)/(\w+)/(\w+)/$', views.search_sum_delta_history_view, name='search_sum_delta_history_view'),

    # 其他零碎功能
    url(r'^spider/monitor/$', views.spider_groups_monitor, name='spider_groups_monitor'),
    url(r'^config/urlsearch/$', views.config_url_search, name='config_url_search'),

    url(r'^test/$', views.select_multiply, name='test'),

]

SVNDev/config/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = True` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin sqlcustom [app_label]'
# into your database.
from __future__ import unicode_literals

from django.db import models
from backend_admin.models import User


class DomainsAll(models.Model):
    domain = models.CharField(max_length=255)


class Locallog(models.Model):
    id = models.CharField(db_column='ID', primary_key=True, max_length=255)  # Field name made lowercase.
    sheng = models.CharField(max_length=255, blank=True, null=True)
    shengid = models.CharField(db_column='shengID', max_length=255, blank=True, null=True)  # Field name made lowercase.
    shi = models.CharField(max_length=255, blank=True, null=True)
    shiid = models.CharField(db_column='shiID', max_length=255, blank=True, null=True)  # Field name made lowercase.
    xian = models.CharField(max_length=255, blank=True, null=True)
    xianid = models.CharField(db_column='xianID', max_length=255, blank=True, null=True)  # Field name made lowercase.
    ip = models.CharField(db_column='IP', max_length=255, blank=True, null=True)  # Field name made lowercase.
    addtime = models.CharField(max_length=255, blank=True, null=True)
    modifytime = models.CharField(max_length=255, blank=True, null=True)
    word = models.CharField(max_length=255, blank=True, null=True)
    diffword = models.CharField(max_length=255, blank=True, null=True)
    author = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'LocalLog'


class B1ClassifyHash(models.Model):
    sl_num = models.IntegerField(primary_key=True)
    sl_code = models.CharField(max_length=50)
    msl_num = models.IntegerField()
    msl_code = models.CharField(max_length=255)
    ctime = models.IntegerField()
    type = models.CharField(max_length=255)

    class Meta:
        managed = True
        db_table = 'b_1classify_hash'


class BArea(models.Model):
    name = models.CharField(max_length=255)
    level = models.IntegerField()
    upid = models.IntegerField()
    fword = models.CharField(max_length=30)

    class Meta:
        managed = True
        db_table = 'b_area'


class BBigdatalog(models.Model):
    job_id = models.IntegerField()
    result_count = models.IntegerField()
    time_cost = models.FloatField()
    term = models.TextField()
    from_version = models.CharField(max_length=20)
    time_stamp = models.CharField(max_length=30)
    topic_id = models.CharField(max_length=50, blank=True, null=True)
    waitting_time = models.FloatField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'b_bigdatalog'


class BClassifyHash(models.Model):
    version_num = models.IntegerField()
    version_code = models.CharField(max_length=40)
    ctime = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'b_classify_hash'


class BClassifyRecord11(models.Model):
    getversion = models.IntegerField()
    returnversion = models.IntegerField()
    time = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'b_classify_record_11'


class BClassifyVersionlog(models.Model):
    version_num = models.IntegerField(primary_key=True)
    version_code = models.CharField(max_length=40)
    ctime = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'b_classify_versionlog'


class BCollectRecord(models.Model):
    time = models.IntegerField()
    c_num = models.IntegerField()
    r_num = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'b_collect_record'


class BWebtype(models.Model):
    typename = models.CharField(max_length=50)

    def __str__(self):
        return self.typename

    class Meta:
        managed = True
        db_table = 'b_webtype'


class Config(models.Model):
    webname = models.CharField(max_length=50, verbose_name='网站名称')
    url = models.CharField(max_length=50, verbose_name='网站域名')
    area = models.CharField(max_length=32, blank=True)
    serveip = models.CharField(db_column='serveIP', max_length=16, blank=True)  # Field name made lowercase.
    servearea = models.CharField(max_length=32, blank=True)
    icp = models.CharField(db_column='ICP', max_length=11, blank=True)  # Field name made lowercase.
    webtype = models.ForeignKey(BWebtype, db_column='webtype')
    channelname = models.CharField(max_length=100, blank=True)
    channelurl = models.TextField(blank=True, )
    savename = models.CharField(max_length=50, )
    savepath = models.CharField(max_length=100, )
    savetime = models.IntegerField()
    filesize = models.IntegerField()
    author = models.CharField(max_length=50)
    last_crawl_time = models.IntegerField(default=0)
    intervaltime = models.IntegerField(default=0)
    gid = models.IntegerField(blank=True, null=True)
    configid = models.IntegerField(blank=True, null=True)
    level = models.IntegerField(blank=True, null=True)
    tags = models.CharField(max_length=50, blank=True, null=True)
    tid = models.IntegerField(blank=True, null=True)
    user = models.ForeignKey(User, db_column='uid', null=True)
    status = models.IntegerField(blank=True, null=True)
    remarks = models.TextField(blank=True, null=True)
    mrid = models.IntegerField(default=0)
    mtid = models.IntegerField(default=0)
    mttid = models.IntegerField(default=0)
    description = models.TextField(default=0)

    class Meta:
        managed = True
        db_table = 'b_conf'


class BConfData(models.Model):
    cid = models.IntegerField()
    content = models.TextField()
    param = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'b_conf_data'


class BConfDomain(models.Model):
    domain = models.CharField(max_length=255)
    domain_name = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'b_conf_domain'


class BConfDomainChannel(models.Model):
    did = models.IntegerField()
    channel = models.TextField()

    class Meta:
        managed = True
        db_table = 'b_conf_domain_channel'


class BConfchannel(models.Model):
    cid = models.IntegerField()
    channelname = models.CharField(max_length=255)
    channelurl = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'b_confchannel'


class BConferror(models.Model):
    worker_id = models.IntegerField()
    config_id = models.CharField(max_length=11)
    error_description = models.TextField(blank=True, null=True)
    config_name = models.CharField(max_length=50)
    end_time = models.IntegerField()
    status = models.IntegerField()
    deal_e = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'b_conferror'


class BConfigtype(models.Model):
    typename = models.CharField(max_length=50)

    class Meta:
        managed = True
        db_table = 'b_configtype'


class BDomain(models.Model):
    id = models.BigIntegerField(primary_key=True)
    site = models.CharField(max_length=100, blank=True, null=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    type = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'b_domain'


class BDomainType(models.Model):
    type = models.CharField(max_length=255, blank=True, null=True)
    type_name = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'b_domain_type'


class BEmail(models.Model):
    email = models.CharField(max_length=50)
    isemail = models.IntegerField()
    isflag = models.IntegerField()
    ext = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'b_email'


class BError(models.Model):
    worker_id = models.IntegerField()
    config_id = models.CharField(max_length=11)
    error_info = models.IntegerField()
    error_description = models.CharField(max_length=50)
    config_name = models.CharField(max_length=50)
    end_time = models.IntegerField()
    status = models.IntegerField()
    deal_e = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'b_error'


class BFile(models.Model):
    filename = models.CharField(max_length=100)
    content = models.TextField()
    site = models.CharField(max_length=50)
    path = models.CharField(max_length=100)
    domains = models.CharField(max_length=100)
    status = models.IntegerField()
    type = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'b_file'


class BFilterRules(models.Model):
    rulesname = models.CharField(max_length=255)
    rule = models.TextField()

    class Meta:
        managed = True
        db_table = 'b_filter_rules'


class BFormatHash(models.Model):
    version_num = models.IntegerField()
    version_code = models.CharField(max_length=40)
    ctime = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'b_format_hash'


class BFormatRecord(models.Model):
    getversion = models.IntegerField()
    returnversion = models.IntegerField()
    time = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'b_format_record'


class BGeturlcs(models.Model):
    webname = models.CharField(max_length=255, blank=True, null=True)
    url = models.CharField(max_length=255, blank=True, null=True)

SVNDev/templates/backend_admin/change_password.html
{% extends 'base_backend.html' %}
{% load static admin_static i18n %}

{% block header_tail %}
    <link rel="stylesheet" href="{% static 'backend/backend_admin/css/style.css' %}">
{% endblock header_tail %}

{% block section_content %}
    <div>
        <div class="box-header with-border">
            <h3 class="box-title">修改{{ username }}密码</h3>
        </div>
        <!-- form start -->
        <div class="box box-primary">
            <div class="box-body">
            {% if username %}
                <span class="no-display" id="change-user-admin">{{ username }}</span>
            {% else %}{% endif %}
                <form id="change_password" role="form" action="{% if username %}{% url 'backend_admin:change_user_password' user_id %}{% else %}{% url 'backend_admin:change_password' %}{% endif %}"
                      method="post">{% csrf_token %}
                    {% for field in change_password_form %}
                        <div class="form-group">
                            <label for="">{{ field.label }}</label>
                            <p>{{ field }}</p>
                            {{ field.help_text }}
                        </div>
                    {% endfor %}

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary" id="change_password_save">确认</button>
                        <button type="submit" class="btn btn-primary" id="change_password_submit" name="_submit"
                                style="display: none">sure
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock section_content %}

{% block jquery_js %}
    <script src='{% static "backend/backend_admin/js/changepassword.js" %}'></script>
{% endblock jquery_js %}

SVNDev/templates/backend_admin/create_user.html
{% extends 'base_backend.html' %}
{% load static %}
{% load backend_admin_filtets %}

{% block header_tail %}
    <link rel="stylesheet" href="{% static 'backend/backend_admin/css/style.css' %}">
{% endblock header_tail %}

{% block section_content %}
    <div>
        <div class="box-header with-border">
            <h3 class="box-title">{% if change %}修改用户{% else %}创建用户{% endif %}</h3>
        </div>
        <div class="box box-primary">
            <div class="box-body">
                <form id="create_user_form" role="form" action="
                        {% if change %}{% url 'backend_admin:change_user' user_id %}{% else %}{% url 'backend_admin:create_user' %}{% endif %}"
                      method="post">{% csrf_token %}
                    {% if change %}
                        <div class="form-group">
                            <span><label for="">用户名：</label></span>
                            <span id="change_username_id">{{ username }}</span>
                        </div>
                        <div class="form-group">
                            <span><label for="">密码：</label></span>
                            <span>密码为加密哈希值，如果修改，请点击<a
                                    href="{% url 'backend_admin:change_user_password' user_id %}">这里</a></span>
                        </div>
                    {% endif %}
                    {% for field in form %}
                        <div class="form-group">
                            {% if field.name == 'is_active' or field.name == 'is_staff' %}
                                {{ field }}<label for="">{{ field.label }}</label>
                                {{ field.help_text }}
                            {% elif field.name == 'groups_permissions' %}
                                <div class="{% if change %}change-margin{% else %}{% endif %}">
                                    <div class="form-group">
                                        <label for="">角色权限</label>
                                        <ul class="ul-no-padding">
                                            {% for permission_group in field %}
                                                {% with group_name=permission_group|striptags %}
                                                    <li class="li-groups user-groups">
                                                        {{ permission_group }}
                                                        <div class="no-display docBubble">
                                                            <p>{{ group_name }}包含权限：</p>
                                                            {% for group_permission in group_name|groups_filter %}
                                                                <ul>
                                                                    <li class="li-group">{{ group_permission.name }}</li>
                                                                </ul>
                                                            {% endfor %}
                                                        </div>
                                                    </li>
                                                {% endwith %}
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                                <div style="clear: both"></div>
                            {% elif field.name == 'permissions' %}
                                <div class="">
                                    {#                            <label for="">个人权限定制</label>#}
                                    {#                            {% for permission_name in field %}#}
                                    {#                                <div class="box-permission">#}
                                    {#                                    <span class="span_permission">{{ permission_name }}</span>#}
                                    {#                                    <ul>#}
                                    {#                                        {% with permission_name=permission_name|striptags %}#}
                                    {#                                            {% autoescape off %}#}
                                    {#                                                {% for permission in permission_name|permission_groups_filter %}#}
                                    {#                                                    <li class="li_permission">#}
                                    {#                                                        <input type="checkbox" name="checkbox_permission"#}
                                    {#                                                               value="{{ permission.name }}">#}
                                    {#                                                        {{ permission.name }}#}
                                    {#                                                    </li>#}
                                    {#                                                {% endfor %}#}
                                    {#                                            {% endautoescape %}#}
                                    {#                                        {% endwith %}#}
                                    {#                                    </ul>#}
                                    {#                                </div>#}
                                    {#                                <br>#}
                                    {#                            {% endfor %}#}
                                </div>
                            {% elif 'config' in field.name %}
                                <label for="">{{ field.label }}</label>
                                <ul class="ul-no-padding">
                                    {% for config_name in field %}
                                        <li class="li-groups">
                                            {{ config_name }}
                                        </li>
                                    {% endfor %}
                                </ul>
                                <div style="clear: both"></div>
                            {% else %}
                                <label for="">{{ field.label }}</label>
                                <p>{{ field }}</p>
                                <p>{{ field.help_text }}</p>
                                {{ field.errors }}
                            {% endif %}
                        </div>

                    {% endfor %}

                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button class="btn btn-primary" id="create_user_button">确认</button>
                        <button type="submit" class="btn btn-primary" id="create_user_submit" name="_save"
                                style="display: none">sure
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock section_content %}


{% block jquery_js %}

    <script type="text/javascript">
        $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
        });
    </script>
    <script src="{% static 'backend/backend_admin/js/createuser.js' %}"></script>


{% endblock jquery_js %}

SVNDev/templates/backend_admin/private.html
{% extends 'base_backend.html' %}
{% load static %}
{% load backend_admin_filtets %}

{% block header_tail %}
    <link rel="stylesheet" href="{% static 'backend/backend_admin/css/style.css' %}">
{% endblock header_tail %}

{% block section_content %}
    <div>
        <div class="box-header with-border">
            <h3 class="box-title">个人中心</h3>
        </div>
        <div class="box box-primary">
            <div class="box-body">
                <div class="box-body">
                    <form id="create_user_form" role="form" action=" {% url 'backend_admin:private' %}" method="post">{% csrf_token %}
                        <div class="form-group">
                            <span><label for="">用户名：</label></span>
                            <span id="change_username_id">{{ username }}</span>
                        </div>
                        <div class="form-group">
                            <span><label for="">密码：</label></span>
                            <span>密码为加密哈希值，如果修改，请点击<a
                                    href="{% url 'backend_admin:change_password' %}">这里</a></span>
                        </div>

                        {% for field in form %}
                            <div class="form-group">
                                <label for="">{{ field.label }}</label>
                                <p>{{ field }}</p>
                                <p>{{ field.help_text }}</p>
                                {{ field.errors }}
                            </div>

                        {% endfor %}

                        <div class="form-group">
                            <span><label for="">权限角色：</label></span>
                            <span id="">{{ role }}</span>
                        </div>

                        {% if perms.backend_admin.view_config %}
                            <div class="form-group">
                                <span><label for="">配置组：</label></span>
                                <span id="">
                        {% for group in group_config_each %}
                            {{ group.name }}，
                        {% endfor %}
                        </span>
                            </div>
                            {% if group_config_manager_len > 0 %}
                                <div class="form-group">
                                    <span><label for="">配置管理组：</label></span>
                                    <span id="">
                                {% for group in group_config_manager %}
                                    {{ group.name }}，
                                {% endfor %}
                            </span>
                                </div>
                            {% endif %}
                        {% endif %}

                        <!-- /.box-footer -->
                        <div class="box-footer">
                            <button class="btn btn-primary" id="create_user_button">确认</button>
                            <button type="submit" class="btn btn-primary" id="create_user_submit" name="_save"
                                    style="display: none">sure
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock section_content %}

{% block jquery_js %}

    <script type="text/javascript">
        $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
        });
    </script>
    <script src="{% static 'backend/backend_admin/js/private.js' %}"></script>


{% endblock jquery_js %}

SVNDev/templates/backend_admin/test.html
{% extends 'base_backend.html' %}
{% load static backend_admin_filtets %}
{% block section_content %}

{% for i in model_list_fields %}
    <p>{{ i }}</p>
{% endfor %}

{% for result in result_list %}
    {{ result }}
    <ul>
        {% for j in result %}
            <li>
                {% if j.value == True %}
                    <img src="{% static 'admin/img/icon-yes.gif' %}" alt="">
                {% elif j.value == False %}
                    <img src="{% static 'admin/img/icon-no.gif' %}" alt="">
                {% else %}
                    {{ j.value }}
                {% endif %}

            </li>
        {% endfor %}
    </ul>
{% endfor %}
{% endblock section_content %}