SVNDev/backend/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

from backend_admin import views as backend_admin_view

handler403 = backend_admin_view.perm_deny
handler404 = backend_admin_view.page_no

urlpatterns = [
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, }),
    url(r'', include('backend_admin.urls', namespace='backend_admin'), ),
    url(r'^config/', include('config.urls', namespace='config'), ),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^allsite/', include('allsite.urls', namespace='allsite'), ),
    url(r'^comments/', include('comments.urls', namespace='comments'), ),
    url(r'^channels/', include('channelConfigMgr.urls', namespace='channels'), ),
]

SVNDev/backend_admin/urls.py
from django.conf.urls import url, patterns
from . import views
from django.views.generic import RedirectView

# from django.views.generic.simple import redirect_to

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login_view, name='login'),
    url(r'^logout$', views.logout_view, name='logout'),
    url(r'^changepassword$', views.change_password, name='change_password'),
    url(r'^private$', views.private, name='private'),
    url(r'^backend_admin/backend_admin/user/add/$', views.create_user, name='create_user', ),
    url(r'^backend_admin/backend_admin/user/(\d+)/password$', views.change_user_password, name='change_user_password', ),
    url(r'^backend_admin/backend_admin/user/(\d+)/$', views.change_user, name='change_user', ),
    url(r'^backend_admin/auth/group/add/$', views.add_group, name='add_group', ),
    url(r'^backend_admin/auth/group/(\d+)/$', views.change_group, name='change_group', ),
    # url(r'^admin/backend_admin/user/\d/$', RedirectView.as_view(url='/changeuser'),),
    # url(r'^admin/auth/group/$', RedirectView.as_view(url='/backend_admin/auth/group', permanent=True), ),

    url(r'^duplicate_username$', views.username_duplicate_verify, name='duplicate_username'),
    url(r'^duplicate_email$', views.email_duplicate_verify, name='duplicate_email'),
    url(r'^backend_admin/(\w+)/(\w+)/$', views.change_list, name='change_list'),
    url(r'^backend_admin/(\w+)/(\w+)/delete$', views.model_object_delete, name='model_object_delete'),

    url(r'^uwsgireload/$', views.reload_uwsgi, name='reload_uwsgi'),
]

SVNDev/config/urls.py
from django.conf.urls import url, patterns
from django.views.generic import RedirectView
# from django.views.generic.simple import redirect_to

from . import views
from config import rest_api


urlpatterns = [
    url(r'^$', views.select_configs, name='select'),
    url(r'^groups/$', views.config_groups_list, name='group'),
    url(r'^groups/(\d+)/$', views.config_group_change, name='each_change'),
    url(r'^groups/add/$', views.config_group_add, name='each_add'),
    url(r'^groups/delete/$', views.config_group_delete, name='each_delete'),
    url(r'^groups/api/$', rest_api.ConfigGroupsListApi.as_view(), name='config_groups_list_api'),

    url(r'^add/$', views.add_config, name='add_config'),
    url(r'^(\d+)/change/$', views.change_config, name='change_config'),
    url(r'^(\d+)/change/history/$', views.change_history, name='change_history'),
    url(r'^diff/$', views.change_config_diff, name='change_diff'),

    # 时间差统计
    url(r'^delta/news/domain/domain$', views.news_user_timedelta_view, name='news_user_timedelta_view'),
    url(r'^delta/news/domain/domain/search/$', views.news_user_timedelta_view, name='news_user_timedelta_view_search'),
    url(r'^delta/news/domain/users/$', views.news_all_user_timedelta_view, name='news_all_user_timedelta_view'),
    url(r'^delta/news/domain/users/search/$', views.news_all_user_timedelta_view, name='news_all_user_timedelta_view_search'),
    url(r'^delta/news/config/config/$', views.config_timedelta_view, name='config_timedelta_view'),
    url(r'^delta/news/config/config/search/$', views.config_timedelta_view, name='config_timedelta_view_search'),
    url(r'^delta/news/config/groupsexclude/$', views.config_groupsexclude_delta, name='config_groupsexclude_delta'),
    url(r'^delta/news/config/groupsexclude/search/$', views.config_groupsexclude_delta, name='config_groupsexclude_delta_search'),

    url(r'^delta/forums/domain/domain$', views.forums_user_timedelta_view, name='forums_user_timedelta_view'),
    url(r'^delta/forums/domain/domain/search/$', views.forums_user_timedelta_view, name='forums_user_timedelta_view_search'),
    url(r'^delta/forums/domain/users/$', views.forums_all_user_timedelta_view, name='forums_all_user_timedelta_view'),
    url(r'^delta/forums/domain/users/search/$', views.forums_all_user_timedelta_view, name='forums_all_user_timedelta_view_search'),
    url(r'^delta/forums/config/config/$', views.forums_config_timedelta_view, name='forums_config_timedelta_view'),
    url(r'^delta/forums/config/config/search/$', views.forums_config_timedelta_view, name='forums_config_timedelta_view_search'),

    url(r'^delta/alldomains/$', views.all_domains_timedelta_view, name='all_domains_timedelta_view'),
    url(r'^delta/alldomains/search/$', views.all_domains_timedelta_view, name='all_domains_timedelta_view_search'),
    url(r'^delta/allconfigs/$', views.all_configs_timedelta_view, name='all_configs_timedelta_view'),
    url(r'^delta/allconfigs/search/$', views.all_configs_timedelta_view, name='all_configs_timedelta_view_search'),

    # 时间差排除
    url(r'^delta/exclude/(\w+)/(\w+)/(\w+)/$', views.exclude_manage, name='exclude_manage'),
    url(r'^delta/excludegroups/(\w+)/(\w+)/(\w+)/$', views.exclude_groups_manage, name='exclude_groups_manage'),

    # 时间差总数
    # url(r'^delta/sum/(\w+)/$', views.sum_deltas, name='sum_deltas'),
    url(r'^delta/basesum/(\w+)/(\w+)/(\w+)/(\S*)/$', views.base_sum_deltas, name='base_sum_deltas'),
    url(r'^delta/ranksum/(\w+)/(\w+)/(\w+)/(\S*)/(\d+)/$', views.rank_sum_deltas, name='rank_sum_deltas'),
    url(r'^delta/customsum/(\w+)/(\w+)/(\w+)/(\S*)/$', views.custom_sum_deltas, name='custom_sum_deltas'),
    url(r'^delta/searchsum/(\w+)/(\w+)/(\w+)/(\S*)/$', views.search_sum_deltas, name='search_sum_deltas'),

    # 时间差历史
    url(r'^delta/history/news/(\w+)/(\w+)/(\S*)/$', views.time_delta_history_view, name='time_delta_history_view'),

    url(r'^delta/history/sum/(\w+)/(\w+)/(\w+)/$', views.sum_delta_history_view, name='sum_delta_history_view'),
    url(r'^delta/history/searchsum/(\w+)/(\w+)/(\w+)/$', views.search_sum_delta_history_view, name='search_sum_delta_history_view'),

    # 其他零碎功能
    url(r'^spider/monitor/$', views.spider_groups_monitor, name='spider_groups_monitor'),
    url(r'^config/urlsearch/$', views.config_url_search, name='config_url_search'),

    url(r'^test/$', views.select_multiply, name='test'),

]

SVNDev/templates/admin_bak/actions.html
{% load i18n %}
<div class="actions">
{#                        <p href="#" class="action-button">#}
{#                            {% blocktrans with cl.opts.verbose_name as name %}删除 {{ name }}{% endblocktrans %}#}
{#                        </p>#}
    {% for field in action_form %}{% if field.label %}<label>{{ field.label }} {% endif %}{{ field }}
    {% if field.label %}</label>{% endif %}{% endfor %}
    <button type="submit" class="button" title="{% trans "Run the selected action" %}" name="index"
            value="{{ action_index|default:0 }}">{% trans "Go" %}</button>
    {% if actions_selection_counter %}
        <script type="text/javascript">var _actions_icnt = "{{ cl.result_list|length|default:"0" }}";</script>
        <span class="action-counter">{{ selection_note }}</span>
        {% if cl.result_count != cl.result_list|length %}
            <span class="all">{{ selection_note_all }}</span>
            <span class="question">
            <a href="javascript:;"
               title="{% trans "Click here to select the objects across all pages" %}">{% blocktrans with cl.result_count as total_count %}
                Select all {{ total_count }} {{ module_name }}{% endblocktrans %}</a>
        </span>
            <span class="clear"><a href="javascript:;">{% trans "Clear selection" %}</a></span>
        {% endif %}
    {% endif %}
</div>
{##}
{#    {% for field in action_form %}#}
{#        {% if field.label %}<label>{{ field.label }}</label>{% endif %}#}
{#        {% if field.name == 'action' %}#}
{#            {% for choice in field.field.choices %}#}
{#                {% if choice.0 != '' %}#}
{#                    <li style="float: left">#}
{#                        <a href="javascript:void(0);" onclick="" class="action-button">#}
{#                            {% if choice.0 == 'delete_selected' %}#}
{#                                删除#}
{#                            {% else %}#}
{#                                {{ choice.0 }}#}
{#                            {% endif %}#}
{#                            {% blocktrans with cl.opts.verbose_name as name %}{{ name }}{% endblocktrans %}#}
{#                        </a>#}
{#                    </li>{% endif %}#}
{#            {% endfor %}#}
{#        {% endif %}#}
{#    {% endfor %}#}
{#</div>#}

SVNDev/templates/admin_bak/base.html
{% extends 'base_backend.html' %}
{% load i18n static admin_static %}
{% block docttype_tail %}
    {% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
{% endblock docttype_tail %}

{% block html_lang %}lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"
{% endif %}{% endblock html_lang %}


{% block header_tail %}
    <link rel="stylesheet" type="text/css"
          href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}"/>
    {% block extrastyle %}{% endblock %}
    <!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="{% block stylesheet_ie %}{% static "admin/css/ie.css" %}{% endblock %}" /><![endif]-->
    {% if LANGUAGE_BIDI %}
        <link rel="stylesheet" type="text/css"
              href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}"/>{% endif %}
    <script type="text/javascript">window.__admin_media_prefix__ = "{% filter escapejs %}{% static "admin/" %}{% endfilter %}";</script>
    <script type="text/javascript">window.__admin_utc_offset__ = "{% filter escapejs %}{% now "Z" %}{% endfilter %}";</script>
    {% block extrahead %}{% endblock %}
    {% block blockbots %}
        <meta name="robots" content="NONE,NOARCHIVE"/>{% endblock %}
{% endblock header_tail %}


{#{% block body_class %}{% if is_popup %}skin-blue popup hold-transition sidebar-mini{% endif %}{% block bodyclass %}{% endblock %}{% endblock body_class %}#}

{% block section_content %}
    <!-- Container -->
    <div id="container" class="">

        {% if not is_popup %}
            <!-- END Header -->
            {#    {% block breadcrumbs %}#}
            {#    <div class="breadcrumbs">#}
            {#    <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>#}
            {#    {% if title %} &rsaquo; {{ title }}{% endif %}#}
            {#    </div>#}
            {#    {% endblock %}#}
        {% endif %}

        {% block messages %}
            {% if messages %}
                <ul class="messagelist">{% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
                {% endfor %}</ul>
            {% endif %}
        {% endblock messages %}

        <!-- Content -->
        <div id="content" class="{% block coltype %}colM{% endblock %}">
            {% block pretitle %}{% endblock %}
            <div class="box-header">
                {% block content_title %}{% if title %}<h3 class="box-title">{{ title }}</h3>{% endif %}{% endblock %}
            </div>
            {% block content %}
                {% block object-tools %}{% endblock %}
                {{ content }}
            {% endblock %}
            {% block sidebar %}{% endblock %}
            <br class="clear"/>
        </div>
        <!-- END Content -->

        {% block footer %}
            <div id="footer"></div>{% endblock %}
    </div>
    <!-- END Container -->

{% endblock section_content %}

SVNDev/templates/admin_bak/base_bak.html
{% extends 'base_backend.html' %}
{% load i18n static admin_static %}
{% block docttype_tail %}
    {% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
{% endblock docttype_tail %}

{% block html_lang %}lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}{% endblock html_lang %}


{% block header_tail %}
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}" />
{% block extrastyle %}{% endblock %}
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="{% block stylesheet_ie %}{% static "admin/css/ie.css" %}{% endblock %}" /><![endif]-->
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}" />{% endif %}
<script type="text/javascript">window.__admin_media_prefix__ = "{% filter escapejs %}{% static "admin/" %}{% endfilter %}";</script>
<script type="text/javascript">window.__admin_utc_offset__ = "{% filter escapejs %}{% now "Z" %}{% endfilter %}";</script>
{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
{% endblock header_tail %}


{#{% block body_class %}{% if is_popup %}skin-blue popup hold-transition sidebar-mini{% endif %}{% block bodyclass %}{% endblock %}{% endblock body_class %}#}

{% block section_content %}
<!-- Container -->
<div id="container" class="box">

    {% if not is_popup %}
    <!-- END Header -->
{#    {% block breadcrumbs %}#}
{#    <div class="breadcrumbs">#}
{#    <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>#}
{#    {% if title %} &rsaquo; {{ title }}{% endif %}#}
{#    </div>#}
{#    {% endblock %}#}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

{% endblock section_content %}

SVNDev/templates/admin_bak/base_site.html
{% extends "admin/base.html" %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">智慧星光管理后台</a></h1>
{% endblock %}

{% block nav-global %}{% endblock %}

SVNDev/templates/admin_bak/change_form.html
{% extends "admin/base_site.html" %}
{% load i18n static admin_urls admin_static admin_modify %}

{% block head_css %}

    <link rel="stylesheet" href="{% static 'backend/backend_admin/css/style.css' %}">
{% endblock head_css %}

{% block extrahead %}{{ block.super }}
    <script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
    {{ media }}
{% endblock %}

{% block extrastyle %}{{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}"/>{% endblock %}

{% block coltype %}colM{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-form{% endblock %}

{% if not is_popup %}
    {% block breadcrumbs %}

    {% endblock %}
{% endif %}

{% block content %}
    <div id="content-main">
        {% block object-tools %}
            {% if change %}{% if not is_popup %}
                <ul class="object-tools">
                    {% block object-tools-items %}
                        <li>
                            {% url opts|admin_urlname:'history' original.pk|admin_urlquote as history_url %}
                            <a href="{% add_preserved_filters history_url %}"
                               class="historylink">{% trans "History" %}</a>
                        </li>
                        {% if has_absolute_url %}
                            <li><a href="{{ absolute_url }}" class="viewsitelink">{% trans "View on site" %}</a></li>
                        {% endif %}
                    {% endblock %}
                </ul>
            {% endif %}{% endif %}
        {% endblock %}
        <form {% if has_file_field %}enctype="multipart/form-data" {% endif %}action="{{ form_url }}" method="post"
              id="{{ opts.model_name }}_form" novalidate>{% csrf_token %}{% block form_top %}{% endblock %}
            <div>
                {% if is_popup %}<input type="hidden" name="{{ is_popup_var }}" value="1"/>{% endif %}
                {% if to_field %}<input type="hidden" name="{{ to_field_var }}" value="{{ to_field }}"/>{% endif %}
                {% if save_on_top %}{% block submit_buttons_top %}{% submit_row %}{% endblock %}{% endif %}
                {% if errors %}
                    <p class="errornote">
                        {% if errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}
                            {% trans "Please correct the errors below." %}{% endif %}
                    </p>
                    {{ adminform.form.non_field_errors }}
                {% endif %}

                {% block field_sets %}
                    {% for fieldset in adminform %}
                        {% include "admin/includes/fieldset.html" %}
                    {% endfor %}
                {% endblock %}

                {% block after_field_sets %}{% endblock %}

                {#                {% block inline_field_sets %}#}
                {#                    {% for inline_admin_formset in inline_admin_formsets %}#}
                {#                        {% include inline_admin_formset.opts.template %}#}
                {#                    {% endfor %}#}
                {#                {% endblock %}#}

                {% block after_related_objects %}{% endblock %}

                {% block submit_buttons_bottom %}{% submit_row %}{% endblock %}

                {% block admin_change_form_document_ready %}
                    <script type="text/javascript">
                        (function ($) {
                            $(document).ready(function () {
                                $('.add-another').click(function (e) {
                                    e.preventDefault();
                                    showAddAnotherPopup(this);
                                });
                                {% if adminform and add %}
                                    $('form#{{ opts.model_name }}_form :input:visible:enabled:first').focus()
                                {% endif %}
                            });

                        })(django.jQuery);
                    </script>
                {% endblock %}

                {# JavaScript for prepopulated fields #}
                {% prepopulated_fields_js %}
            </div>
        </form>
    </div>
{% endblock %}

{% block jquery_js %}
    <script src="{% static 'backend/backend_admin/js/passwordform.js' %}"></script>
{% endblock jquery_js %}

SVNDev/templates/admin_bak/change_list_results.html
{% load i18n admin_static %}
{% if result_hidden_fields %}
<div class="hiddenfields">{# DIV for HTML validation #}
{% for item in result_hidden_fields %}{{ item }}{% endfor %}
</div>
{% endif %}
{% if results %}
<div class="results">
<table id="result_list" class="table table-bordered table-striped">
<thead>
<tr>
{% for header in result_headers %}
<th scope="col" {{ header.class_attrib }}>
   {% if header.sortable %}
     {% if header.sort_priority > 0 %}
       <div class="sortoptions">
         <a class="sortremove" href="{{ header.url_remove }}" title="{% trans "Remove from sorting" %}"></a>
         {% if num_sorted_fields > 1 %}<span class="sortpriority" title="{% blocktrans with priority_number=header.sort_priority %}Sorting priority: {{ priority_number }}{% endblocktrans %}">{{ header.sort_priority }}</span>{% endif %}
         <a href="{{ header.url_toggle }}" class="toggle {% if header.ascending %}ascending{% else %}descending{% endif %}" title="{% trans "Toggle sorting" %}"></a>
       </div>
     {% endif %}
   {% endif %}
   <div class="text">{% if header.sortable %}<a href="{{ header.url_primary }}">{{ header.text|capfirst }}</a>{% else %}<span>{{ header.text|capfirst }}</span>{% endif %}</div>
   <div class="clear"></div>
</th>{% endfor %}
</tr>
</thead>
<tbody>
{% for result in results %}
{% if result.form.non_field_errors %}
    <tr><td colspan="{{ result|length }}">{{ result.form.non_field_errors }}</td></tr>
{% endif %}
<tr class="{% cycle 'row1' 'row2' %}">{% for item in result %}{{ item }}{% endfor %}</tr>
{% endfor %}
</tbody>
</table>
</div>
{% endif %}

SVNDev/templates/admin_bak/login.html
<!-- /.login-box -->

{% extends 'lib/_base.html' %}

{% block header_tail %}
    <style type="text/css">
        body {
            background-color: #606c84;
        }

        .row {
            margin-top: 90px;
        }

        @media (min-width: 768px) {
            .form-signin {
                max-width: 380px;
                margin: 0 auto 20px;
                background-color: #fff;
                border: 1px solid #e5e5e5;
                -webkit-border-radius: 5px;
                -moz-border-radius: 5px;
                border-radius: 5px;
                -webkit-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
                -moz-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
                box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
            }

            .form-signin-inner {
                padding: 9px 29px 29px;
            }

            .form-signin .form-signin-heading, .form-signin .checkbox, .form-signin h2 {
                margin-bottom: 30px;
            }

            .form-signin .form-actions {
                margin: 0;
            }

            #id_username, #id_password {
                display: block;
                font-size: 16px;
                height: 44px;
                width: 100%;
            }
        }
    </style>
{% endblock %}

{% block wrapper_content %}
    <div class="login">
        <div class="container">

            <!-- Header -->
            <div class="navbar navbar-default navbar-fixed-top">
                <div class="navbar-inner">
                    <div class="container">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse"
                                    data-target="#header-navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>

                            <a class="navbar-brand" href="/admin/">智慧星光采集后台</a>

                        </div>
                        <div id="header-navbar-collapse" class="navbar-collapse collapse navbar-right">
                            <ul class="nav navbar-nav">


                            </ul>
                        </div><!--/.nav-collapse -->
                    </div>
                </div>
            </div>
            <!-- END Header -->
            <div class="row">
                <div class="col-sm-12">

                </div>
            </div>


            <!-- Content -->
            <div id="content" class="colM">


                <div id="content-main">
                    <form class="form-signin" action="{% url 'backend_admin:login' %}" method="post" id="login-form">
                        {% csrf_token %}
                        <div class="form-signin-inner">
                            <h2>Login</h2>
                            {% if content or messages %}
                                <div class="alert alert-danger">
                                    <ul class="messages">
                                        {% for message in messages %}
                                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                        {% endfor %}
                                    </ul>
                                    <span>{{ content }}</span>
                                </div>
                            {% endif %}


                            <div class="form-group">
                                <label class="required" for="id_username">用户名:</label>
                                <p class="text-danger"></p>
                                <input class="form-control" id="id_username" maxlength="254" name="username"
                                       placeholder="用户名" required="required" title="" type="text"/>
                            </div>
                            <div class="form-group">
                                <label class="required" for="id_password">密码:</label>
                                <p class="text-danger"></p>
                                <input class="form-control" id="id_password" name="password" placeholder="密码"
                                       required="required" title="" type="password"/>
                                <input type="hidden" name="next" value="/admin/"/>
                            </div>


                            <div class="form-actions clearfix">
                                <input type="submit" value="登录" class="btn btn-lg btn-primary btn-block"/>
                            </div>
                        </div>
                    </form>

                    <script type="text/javascript">
                        $(document).ready(function () {
                            $('#id_username').attr('autocapitalize', 'off').focus();
                        })
                    </script>
                </div>


            </div>
            <!-- END Content -->
        </div>
    </div>
    <!-- /.login-box -->
{% endblock wrapper_content %}


{% block body_js %}
    <!-- jQuery 2.2.3 -->
    <script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' // optional
            });
        });
    </script>
{% endblock body_js %}