SVNDev/backend/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

from backend_admin import views as backend_admin_view

handler403 = backend_admin_view.perm_deny
handler404 = backend_admin_view.page_no

urlpatterns = [
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, }),
    url(r'', include('backend_admin.urls', namespace='backend_admin'), ),
    url(r'^config/', include('config.urls', namespace='config'), ),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^allsite/', include('allsite.urls', namespace='allsite'), ),
    url(r'^comments/', include('comments.urls', namespace='comments'), ),
    url(r'^channels/', include('channelConfigMgr.urls', namespace='channels'), ),
]

SVNDev/backend_admin/urls.py
from django.conf.urls import url, patterns
from . import views
from django.views.generic import RedirectView

# from django.views.generic.simple import redirect_to

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login_view, name='login'),
    url(r'^logout$', views.logout_view, name='logout'),
    url(r'^changepassword$', views.change_password, name='change_password'),
    url(r'^private$', views.private, name='private'),
    url(r'^backend_admin/backend_admin/user/add/$', views.create_user, name='create_user', ),
    url(r'^backend_admin/backend_admin/user/(\d+)/password$', views.change_user_password, name='change_user_password', ),
    url(r'^backend_admin/backend_admin/user/(\d+)/$', views.change_user, name='change_user', ),
    url(r'^backend_admin/auth/group/add/$', views.add_group, name='add_group', ),
    url(r'^backend_admin/auth/group/(\d+)/$', views.change_group, name='change_group', ),
    # url(r'^admin/backend_admin/user/\d/$', RedirectView.as_view(url='/changeuser'),),
    # url(r'^admin/auth/group/$', RedirectView.as_view(url='/backend_admin/auth/group', permanent=True), ),

    url(r'^duplicate_username$', views.username_duplicate_verify, name='duplicate_username'),
    url(r'^duplicate_email$', views.email_duplicate_verify, name='duplicate_email'),
    url(r'^backend_admin/(\w+)/(\w+)/$', views.change_list, name='change_list'),
    url(r'^backend_admin/(\w+)/(\w+)/delete$', views.model_object_delete, name='model_object_delete'),

    url(r'^uwsgireload/$', views.reload_uwsgi, name='reload_uwsgi'),
]

SVNDev/config/urls.py
from django.conf.urls import url, patterns
from django.views.generic import RedirectView
# from django.views.generic.simple import redirect_to

from . import views
from config import rest_api


urlpatterns = [
    url(r'^$', views.select_configs, name='select'),
    url(r'^groups/$', views.config_groups_list, name='group'),
    url(r'^groups/(\d+)/$', views.config_group_change, name='each_change'),
    url(r'^groups/add/$', views.config_group_add, name='each_add'),
    url(r'^groups/delete/$', views.config_group_delete, name='each_delete'),
    url(r'^groups/api/$', rest_api.ConfigGroupsListApi.as_view(), name='config_groups_list_api'),

    url(r'^add/$', views.add_config, name='add_config'),
    url(r'^(\d+)/change/$', views.change_config, name='change_config'),
    url(r'^(\d+)/change/history/$', views.change_history, name='change_history'),
    url(r'^diff/$', views.change_config_diff, name='change_diff'),

    # 时间差统计
    url(r'^delta/news/domain/domain$', views.news_user_timedelta_view, name='news_user_timedelta_view'),
    url(r'^delta/news/domain/domain/search/$', views.news_user_timedelta_view, name='news_user_timedelta_view_search'),
    url(r'^delta/news/domain/users/$', views.news_all_user_timedelta_view, name='news_all_user_timedelta_view'),
    url(r'^delta/news/domain/users/search/$', views.news_all_user_timedelta_view, name='news_all_user_timedelta_view_search'),
    url(r'^delta/news/config/config/$', views.config_timedelta_view, name='config_timedelta_view'),
    url(r'^delta/news/config/config/search/$', views.config_timedelta_view, name='config_timedelta_view_search'),
    url(r'^delta/news/config/groupsexclude/$', views.config_groupsexclude_delta, name='config_groupsexclude_delta'),
    url(r'^delta/news/config/groupsexclude/search/$', views.config_groupsexclude_delta, name='config_groupsexclude_delta_search'),

    url(r'^delta/forums/domain/domain$', views.forums_user_timedelta_view, name='forums_user_timedelta_view'),
    url(r'^delta/forums/domain/domain/search/$', views.forums_user_timedelta_view, name='forums_user_timedelta_view_search'),
    url(r'^delta/forums/domain/users/$', views.forums_all_user_timedelta_view, name='forums_all_user_timedelta_view'),
    url(r'^delta/forums/domain/users/search/$', views.forums_all_user_timedelta_view, name='forums_all_user_timedelta_view_search'),
    url(r'^delta/forums/config/config/$', views.forums_config_timedelta_view, name='forums_config_timedelta_view'),
    url(r'^delta/forums/config/config/search/$', views.forums_config_timedelta_view, name='forums_config_timedelta_view_search'),

    url(r'^delta/alldomains/$', views.all_domains_timedelta_view, name='all_domains_timedelta_view'),
    url(r'^delta/alldomains/search/$', views.all_domains_timedelta_view, name='all_domains_timedelta_view_search'),
    url(r'^delta/allconfigs/$', views.all_configs_timedelta_view, name='all_configs_timedelta_view'),
    url(r'^delta/allconfigs/search/$', views.all_configs_timedelta_view, name='all_configs_timedelta_view_search'),

    # 时间差排除
    url(r'^delta/exclude/(\w+)/(\w+)/(\w+)/$', views.exclude_manage, name='exclude_manage'),
    url(r'^delta/excludegroups/(\w+)/(\w+)/(\w+)/$', views.exclude_groups_manage, name='exclude_groups_manage'),

    # 时间差总数
    # url(r'^delta/sum/(\w+)/$', views.sum_deltas, name='sum_deltas'),
    url(r'^delta/basesum/(\w+)/(\w+)/(\w+)/(\S*)/$', views.base_sum_deltas, name='base_sum_deltas'),
    url(r'^delta/ranksum/(\w+)/(\w+)/(\w+)/(\S*)/(\d+)/$', views.rank_sum_deltas, name='rank_sum_deltas'),
    url(r'^delta/customsum/(\w+)/(\w+)/(\w+)/(\S*)/$', views.custom_sum_deltas, name='custom_sum_deltas'),
    url(r'^delta/searchsum/(\w+)/(\w+)/(\w+)/(\S*)/$', views.search_sum_deltas, name='search_sum_deltas'),

    # 时间差历史
    url(r'^delta/history/news/(\w+)/(\w+)/(\S*)/$', views.time_delta_history_view, name='time_delta_history_view'),

    url(r'^delta/history/sum/(\w+)/(\w+)/(\w+)/$', views.sum_delta_history_view, name='sum_delta_history_view'),
    url(r'^delta/history/searchsum/(\w+)/(\w+)/(\w+)/$', views.search_sum_delta_history_view, name='search_sum_delta_history_view'),

    # 其他零碎功能
    url(r'^spider/monitor/$', views.spider_groups_monitor, name='spider_groups_monitor'),
    url(r'^config/urlsearch/$', views.config_url_search, name='config_url_search'),

    url(r'^test/$', views.select_multiply, name='test'),

]

SVNDev/uploads/configs/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # ex: /polls/123123123
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login_view, name='login'),
    url(r'^logout$', views.do_logout, name='logout'),
    url(r'^changepassword$', views.change_password, name='change_password'),
]

SVNDev/config/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = True` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin sqlcustom [app_label]'
# into your database.
from __future__ import unicode_literals

from django.db import models
from backend_admin.models import User


class DomainsAll(models.Model):
    domain = models.CharField(max_length=255)


class Locallog(models.Model):
    id = models.CharField(db_column='ID', primary_key=True, max_length=255)  # Field name made lowercase.
    sheng = models.CharField(max_length=255, blank=True, null=True)
    shengid = models.CharField(db_column='shengID', max_length=255, blank=True, null=True)  # Field name made lowercase.
    shi = models.CharField(max_length=255, blank=True, null=True)
    shiid = models.CharField(db_column='shiID', max_length=255, blank=True, null=True)  # Field name made lowercase.
    xian = models.CharField(max_length=255, blank=True, null=True)
    xianid = models.CharField(db_column='xianID', max_length=255, blank=True, null=True)  # Field name made lowercase.
    ip = models.CharField(db_column='IP', max_length=255, blank=True, null=True)  # Field name made lowercase.
    addtime = models.CharField(max_length=255, blank=True, null=True)
    modifytime = models.CharField(max_length=255, blank=True, null=True)
    word = models.CharField(max_length=255, blank=True, null=True)
    diffword = models.CharField(max_length=255, blank=True, null=True)
    author = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'LocalLog'


class B1ClassifyHash(models.Model):
    sl_num = models.IntegerField(primary_key=True)
    sl_code = models.CharField(max_length=50)
    msl_num = models.IntegerField()
    msl_code = models.CharField(max_length=255)
    ctime = models.IntegerField()
    type = models.CharField(max_length=255)

    class Meta:
        managed = True
        db_table = 'b_1classify_hash'


class BArea(models.Model):
    name = models.CharField(max_length=255)
    level = models.IntegerField()
    upid = models.IntegerField()
    fword = models.CharField(max_length=30)

    class Meta:
        managed = True
        db_table = 'b_area'


class BBigdatalog(models.Model):
    job_id = models.IntegerField()
    result_count = models.IntegerField()
    time_cost = models.FloatField()
    term = models.TextField()
    from_version = models.CharField(max_length=20)
    time_stamp = models.CharField(max_length=30)
    topic_id = models.CharField(max_length=50, blank=True, null=True)
    waitting_time = models.FloatField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'b_bigdatalog'


class BClassifyHash(models.Model):
    version_num = models.IntegerField()
    version_code = models.CharField(max_length=40)
    ctime = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'b_classify_hash'


class BClassifyRecord11(models.Model):
    getversion = models.IntegerField()
    returnversion = models.IntegerField()
    time = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'b_classify_record_11'


class BClassifyVersionlog(models.Model):
    version_num = models.IntegerField(primary_key=True)
    version_code = models.CharField(max_length=40)
    ctime = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'b_classify_versionlog'


class BCollectRecord(models.Model):
    time = models.IntegerField()
    c_num = models.IntegerField()
    r_num = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'b_collect_record'


class BWebtype(models.Model):
    typename = models.CharField(max_length=50)

    def __str__(self):
        return self.typename

    class Meta:
        managed = True
        db_table = 'b_webtype'


class Config(models.Model):
    webname = models.CharField(max_length=50, verbose_name='网站名称')
    url = models.CharField(max_length=50, verbose_name='网站域名')
    area = models.CharField(max_length=32, blank=True)
    serveip = models.CharField(db_column='serveIP', max_length=16, blank=True)  # Field name made lowercase.
    servearea = models.CharField(max_length=32, blank=True)
    icp = models.CharField(db_column='ICP', max_length=11, blank=True)  # Field name made lowercase.
    webtype = models.ForeignKey(BWebtype, db_column='webtype')
    channelname = models.CharField(max_length=100, blank=True)
    channelurl = models.TextField(blank=True, )
    savename = models.CharField(max_length=50, )
    savepath = models.CharField(max_length=100, )
    savetime = models.IntegerField()
    filesize = models.IntegerField()
    author = models.CharField(max_length=50)
    last_crawl_time = models.IntegerField(default=0)
    intervaltime = models.IntegerField(default=0)
    gid = models.IntegerField(blank=True, null=True)
    configid = models.IntegerField(blank=True, null=True)
    level = models.IntegerField(blank=True, null=True)
    tags = models.CharField(max_length=50, blank=True, null=True)
    tid = models.IntegerField(blank=True, null=True)
    user = models.ForeignKey(User, db_column='uid', null=True)
    status = models.IntegerField(blank=True, null=True)
    remarks = models.TextField(blank=True, null=True)
    mrid = models.IntegerField(default=0)
    mtid = models.IntegerField(default=0)
    mttid = models.IntegerField(default=0)
    description = models.TextField(default=0)

    class Meta:
        managed = True
        db_table = 'b_conf'


class BConfData(models.Model):
    cid = models.IntegerField()
    content = models.TextField()
    param = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'b_conf_data'


class BConfDomain(models.Model):
    domain = models.CharField(max_length=255)
    domain_name = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'b_conf_domain'


class BConfDomainChannel(models.Model):
    did = models.IntegerField()
    channel = models.TextField()

    class Meta:
        managed = True
        db_table = 'b_conf_domain_channel'


class BConfchannel(models.Model):
    cid = models.IntegerField()
    channelname = models.CharField(max_length=255)
    channelurl = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'b_confchannel'


class BConferror(models.Model):
    worker_id = models.IntegerField()
    config_id = models.CharField(max_length=11)
    error_description = models.TextField(blank=True, null=True)
    config_name = models.CharField(max_length=50)
    end_time = models.IntegerField()
    status = models.IntegerField()
    deal_e = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'b_conferror'


class BConfigtype(models.Model):
    typename = models.CharField(max_length=50)

    class Meta:
        managed = True
        db_table = 'b_configtype'


class BDomain(models.Model):
    id = models.BigIntegerField(primary_key=True)
    site = models.CharField(max_length=100, blank=True, null=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    type = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'b_domain'


class BDomainType(models.Model):
    type = models.CharField(max_length=255, blank=True, null=True)
    type_name = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'b_domain_type'


class BEmail(models.Model):
    email = models.CharField(max_length=50)
    isemail = models.IntegerField()
    isflag = models.IntegerField()
    ext = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'b_email'


class BError(models.Model):
    worker_id = models.IntegerField()
    config_id = models.CharField(max_length=11)
    error_info = models.IntegerField()
    error_description = models.CharField(max_length=50)
    config_name = models.CharField(max_length=50)
    end_time = models.IntegerField()
    status = models.IntegerField()
    deal_e = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'b_error'


class BFile(models.Model):
    filename = models.CharField(max_length=100)
    content = models.TextField()
    site = models.CharField(max_length=50)
    path = models.CharField(max_length=100)
    domains = models.CharField(max_length=100)
    status = models.IntegerField()
    type = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'b_file'


class BFilterRules(models.Model):
    rulesname = models.CharField(max_length=255)
    rule = models.TextField()

    class Meta:
        managed = True
        db_table = 'b_filter_rules'


class BFormatHash(models.Model):
    version_num = models.IntegerField()
    version_code = models.CharField(max_length=40)
    ctime = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'b_format_hash'


class BFormatRecord(models.Model):
    getversion = models.IntegerField()
    returnversion = models.IntegerField()
    time = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'b_format_record'


class BGeturlcs(models.Model):
    webname = models.CharField(max_length=255, blank=True, null=True)
    url = models.CharField(max_length=255, blank=True, null=True)

SVNDev/templates/config/config_group.html
{% extends 'base_backend.html' %}
{% load static admin_static i18n %}
{% load backend_admin_filtets %}

{% block header_tail %}
    <link rel="stylesheet" href="{% static 'backend/backend_admin/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}">
{% endblock header_tail %}

{% block section_content %}
    <div>
        <div class="box-header with-border">
            <h3 class="box-title">配置分组管理</h3>
        </div>
        <!-- form start -->
        <div class="box box-primary">
            <div class="box-header">
                <a href="{% url 'config:each_add' %}">
                    <button class="btn " id="create_config_group">增加配置分组</button>
                </a>
                <button class="btn " id="delete_config_group"><a href="#">删除配置分组</a></button>
            </div>
            <div class="box-body">
                <form id="config_group_form" role="form"
                      action="{% if delete %}{% url 'config:each_delete' %}{% else %}{% endif %}"
                      method="post">{% csrf_token %}

                    <div class="group">

                        <table id="config_each_table" border="1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th class="action-checkbox"><input type="checkbox" name="th_checkbox"></th>
                                <th>配置组</th>
                                <th>创建者</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for i in groups %}
                                <tr>
                                    <td class="action-checkbox"><input type="checkbox" name="td_checkbox"
                                                                       value="{{ i.pk }}"></td>
                                    <td><a href="{% url 'config:each_change' i.pk %}">{{ i.name }}</a></td>
                                    <td>{{ i.user.nickname }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                    <!-- /.box-footer -->
                    <div class="box-footer">
                        <button class="btn btn-primary no-display" id="submit_button">确认</button>
                        <button type="submit" class="btn btn-primary" id="save_submit" name="_save"
                                style="display: none">sure
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock section_content %}

{% block body_js %}
    {{ block.super }}

    <!-- DataTables -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>


    <script>
        $(function () {

            $('#delete_config_group').click(function () {
                alert('delete');
                $('#config_group_form').attr('action', '{% url "config:each_delete" %}');
                $('#submit_button').click();
            });
            $("#config_each_table").DataTable({
                "columnDefs": [
                    {"orderable": false, "targets": 0}
                ],
                "order": [[1, 'dec'],],
                "language": {
                    "emptyTable": "没有匹配的数据",
                    "info": "_START_ to _END_ of _TOTAL_",
                    "infoEmpty": "0 of _MAX_",
                    "infoFiltered": "",
                    "lengthMenu": "显示 _MENU_ 条",
                    "search": "搜索:",
                    "zeroRecords": "没有匹配的数据",
                    "paginate": {
                        "first": "首页",
                        "last": "尾页",
                        "next": "下一页",
                        "previous": "上一页"
                    },
                }
            });
            $('.action-checkbox').css('width', '3px');
            $('.action-checkbox').css('padding-right', '3px');
        });


        // 删除时的选择
        $('input[name="th_checkbox"]').click(function () {
            var children_checkboxes = $(this).closest('#config_each_table').find('input[name="td_checkbox"]');
            if ($(this).prop('checked') == true) {
                $(this).attr("checked", true);
                children_checkboxes.each(function () {
                    $(this).prop("checked", "checked");
                })
            } else {
                $(this).attr("checked", false);
                children_checkboxes.each(function () {
                    $(this).removeAttr('checked')
                })
            }
        });

        $('input[name="td_checkbox"]').click(function () {
            var parent_checkbox = $(this).closest('#config_each_table').find('input[name="th_checkbox"]');
            var children_checkboxes = $(this).closest('#config_each_table').find('input[name="td_checkbox"]');
            var checked_num = 0;
            children_checkboxes.each(function () {
                if ($(this).prop('checked') == true) {
                    checked_num += 1
                }
            });
            if (checked_num == children_checkboxes.length) {
                parent_checkbox.prop("checked", "checked");
            } else {
                parent_checkbox.removeAttr('checked')
            }
        });
    </script>
{% endblock body_js %}

SVNDev/templates/config/config_list.html
{% extends 'base_backend.html' %}
{% load static admin_static i18n %}
{% load backend_admin_filtets %}

{% block header_tail %}
    <link rel="stylesheet" href="{% static 'backend/backend_admin/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}">
{% endblock header_tail %}

{% block section_content %}
    <div>
        <div class="box-header with-border">
            <h3 class="box-title">{{ model_verbose_name }}查询</h3>
        </div>
        <!-- form start -->
        <div class="box box-primary">
            <div class="box-header">
                {% if delete_perm_verify %}
                    <button class="btn " id="model_delete"><a href="#">删除{{ model_verbose_name }}</a></button>
                {% endif %}
            </div>
            <div class="box-body">
                <form id="model_form" role="form"
                      action="{% url 'backend_admin:model_object_delete' app_label model_name %}"
                      method="post">{% csrf_token %}

                    <div class="group">

                        <table id="config_each_table" border="1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th class="action-checkbox"><input type="checkbox" name="th_checkbox"></th>
                                {% for field in model_list_fields %}
                                    <th>{{ field }}</th>
                                {% endfor %}
                            </tr>
                            </thead>
                            <tbody>
                            {% for item in topics.object_list %}
                                <tr>
                                    <td class="action-checkbox"><input type="checkbox" name="td_checkbox"
                                                                       value="{{ result.id }}"></td>

                                    <td><a href="{% url 'config:change_config' item.id %}">{{ item.id }}</a></td>
                                    <td>{{ item.webname }}</td>
                                    <td>{{ item.url }}</td>
                                    <td>{{ item.savename }}</td>
                                    <td>{{ item.author }}</td>
                                    <td>{{ item.savetime }}</td>


                                    <td>
                                        {% if perms.backend_admin.begin_config %}
                                            启动
                                        {% endif %}
                                        {% if perms.backend_admin.view_config_detail %}
                                            | 详情
                                        {% endif %}
                                        {% if perms.backend_admin.delete_config %}
                                            | 删除
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <p>
                            {% if topics.has_previous %}
                                <a href="?page={{ topics.previous_page_number }}">Previous</a>
                            {% endif %}
                            Page {{ topics.number }} of {{ topics.paginator.num_pages }}
                            {% if topics.has_next %}
                                <a href="?page={{ topics.next_page_number }}">Next</a>
                            {% endif %}
                        </p>
                    </div>

                    <!-- /.box-footer -->
                    <div class="box-footer">
                        <button class="btn btn-primary no-display" id="submit_button">确认</button>
                        <button type="submit" class="btn btn-primary" id="save_submit" name="_save"
                                style="display: none">sure
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock section_content %}

{% block body_js %}
    {{ block.super }}

    <!-- DataTables -->
    {#    <script src="{% static 'plugins/datatables/jquery.dataTables.js' %}"></script>#}
    {#    <script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>#}


    <script>
        $(function () {

            $('#model_delete').click(function () {
                alert('您确定要删除吗？');
                $('#model_form').attr('action', '{% url 'backend_admin:model_object_delete' app_label model_name%}');
                $('#submit_button').click();
            });
            {#            $("#config_each_table").DataTable({#}
            {#                "columnDefs": [#}
            {#                    {"orderable": false, "targets": 0}#}
            {#                ],#}
            {#                "order": [[1, 'dec'],],#}
            {#                "language": {#}
            {#                    "emptyTable": "没有匹配的数据",#}
            {#                    "info": "_START_ to _END_ of _TOTAL_",#}
            {#                    "infoEmpty": "0 of _MAX_",#}
            {#                    "infoFiltered": "",#}
            {#                    "lengthMenu": "显示 _MENU_ 条",#}
            {#                    "search": "搜索:",#}
            {#                    "zeroRecords": "没有匹配的数据",#}
            {#                    "paginate": {#}
            {#                        "first": "首页",#}
            {#                        "last": "尾页",#}
            {#                        "next": "下一页",#}
            {#                        "previous": "上一页"#}
            {#                    },#}
            {#                }#}
            {#            });#}
            {#            $('.action-checkbox').css('width', '3px');#}
            {#            $('.action-checkbox').css('padding-right', '3px');#}
            {#        });#}


            // 删除时的选择
            $('input[name="th_checkbox"]').click(function () {
                var children_checkboxes = $(this).closest('#config_each_table').find('input[name="td_checkbox"]');
                if ($(this).prop('checked') == true) {
                    $(this).attr("checked", true);
                    children_checkboxes.each(function () {
                        $(this).prop("checked", "checked");
                    })
                } else {
                    $(this).attr("checked", false);
                    children_checkboxes.each(function () {
                        $(this).removeAttr('checked')
                    })
                }
            });

            $('input[name="td_checkbox"]').click(function () {
                var parent_checkbox = $(this).closest('#config_each_table').find('input[name="th_checkbox"]');
                var children_checkboxes = $(this).closest('#config_each_table').find('input[name="td_checkbox"]');
                var checked_num = 0;
                children_checkboxes.each(function () {
                    if ($(this).prop('checked') == true) {
                        checked_num += 1
                    }
                });
                if (checked_num == children_checkboxes.length) {
                    parent_checkbox.prop("checked", "checked");
                } else {
                    parent_checkbox.removeAttr('checked')
                }
            });
             });
    </script>
{% endblock body_js %}

SVNDev/templates/config/each.html
{% extends 'base_backend.html' %}
{% load static admin_static i18n %}

{% block header_tail %}
    <link rel="stylesheet" href="{% static 'backend/backend_admin/css/style.css' %}">
{% endblock header_tail %}

{% block section_content %}
    <div>
        <div class="box-header with-border">
            <h3 class="box-title">配置分组</h3>
        </div>
        <!-- form start -->
        <div class="box box-primary">
            <div class="box-body">
                <table border="1" class="table table-bordered table-striped dataTable">
                    <tr>
                        <th>分组名称</th>
                        <th>创建者</th>
                    </tr>
                    {% for i in groups %}
                        <tr>
                            <td>{{ i.name }}</td>
                            <td>{{ i.user.nickname }}</td>
                        </tr>
                    {% endfor %}

                </table>

            </div>
        </div>
    </div>
{% endblock section_content %}